### ISSUE TITLE
Trying to meassure using CTRL in V11

### ISSUE THREAD

**Issue by Bryn1701** [manuelVo/foundryvtt-drag-ruler#302]
As the title says, there is an error when trying to measure while holding CTRL. Not only doesn't it measure and bring up a NAN total, but the error messages start popping up for every 5 feet measured. 

V11 308
D&D 5e 2.3.1

Here is the error message and picture. 

rulerScale.js:87 Uncaught TypeError: this._highlightMeasurement is not a function
    at DragRulerRuler.newMeasure (rulerScale.js:87:14)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:591:14)
    at 🎁Ruler.prototype.measure#0 (libWrapper-wrapper.js:189:20)
    at DragRulerRuler.measure (ruler.js:81:18)
    at DragRulerRuler._onMouseMove (foundry.js:37430:12)
    at Canvas._onDragLeftMove (foundry.js:27339:42)
    at MouseInteractionManager.callback (foundry.js:31655:17)
    at #handleDragMove (foundry.js:32002:26)
    at #handleMouseMove (foundry.js:31974:37)
    at Na.notifyListeners (earcut.js:128:75)
    at Na.notifyTarget (earcut.js:128:75)
    at Na.propagate (earcut.js:128:75)
    at Na.dispatchEvent (earcut.js:128:75)
    at Na.mapPointerMove (earcut.js:128:75)
    at Na.mapEvent (earcut.js:128:75)
    at yn.onPointerMove (earcut.js:128:75)

![Broken Drag Ruler](https://github.com/manuelVo/foundryvtt-drag-ruler/assets/64208580/c632b9e7-684c-4ac1-a43e-2e52f0f7fc5a)

**Comment by Bryn1701** [comment]
Was not this modules issue.
