### ISSUE TITLE
V12 Compatibility - freezes tokens

### ISSUE THREAD

**Issue by apoapostolov** [manuelVo/foundryvtt-drag-ruler#324]
Tokens are frozen and canvas crashes when Drag Ruler is active. 

```
ruler.js:108 Uncaught TypeError: Cannot read properties of null (reading 'x')
    at DragRulerRuler.measure (ruler.js:108:33)
    at DragRulerRuler.scheduleMeasurement (foundry_imports.js:153:8)
    at DragRulerRuler.onMouseMove (foundry_imports.js:145:22)
    at TokenPF2e.onEntityLeftDragMove (main.js:159:37)
    at TokenPF2e.onEntityLeftDragMoveSnap (main.js:153:23)
    at 🎁Token.prototype._onDragLeftMove#0 (libWrapper-wrapper.js:187:52)
    at MouseInteractionManager.callback (foundry.js:30498:17)
    at #handleDragMove (foundry.js:30877:26)
    at #handlePointerMove (foundry.js:30842:64)
    at vh.notifyListeners (EventBoundary.ts:1464:33)
    at vh.notifyTarget (EventBoundary.ts:658:14)
    at vh.propagate (EventBoundary.ts:310:18)
    at vh.dispatchEvent (EventBoundary.ts:210:14)
    at vh.mapPointerMove (EventBoundary.ts:815:64)
    at vh.mapEvent (EventBoundary.ts:231:28)
    at ra.onPointerMove (EventSystem.ts:396:31)
    at MouseInteractionManager.<anonymous> (foundry.js:30407:23)
    at foundry-esm.js:2712:18
ruler.js:108 Uncaught TypeError: Cannot read properties of null (reading 'x')
    at DragRulerRuler.measure (ruler.js:108:33)
    at DragRulerRuler.scheduleMeasurement (foundry_imports.js:153:8)
    at DragRulerRuler.onMouseMove (foundry_imports.js:145:22)
    at TokenPF2e.onEntityLeftDragMove (main.js:159:37)
    at TokenPF2e.onEntityLeftDragMoveSnap (main.js:153:23)
    at 🎁Token.prototype._onDragLeftMove#0 (libWrapper-wrapper.js:187:52)
    at MouseInteractionManager.callback (foundry.js:30498:17)
    at #handleDragMove (foundry.js:30877:26)
    at #handlePointerMove (foundry.js:30842:64)
    at vh.notifyListeners (EventBoundary.ts:1464:33)
    at vh.notifyTarget (EventBoundary.ts:658:14)
    at vh.propagate (EventBoundary.ts:310:18)
    at vh.dispatchEvent (EventBoundary.ts:210:14)
    at vh.mapPointerMove (EventBoundary.ts:815:64)
    at vh.mapEvent (EventBoundary.ts:231:28)
    at ra.onPointerMove (EventSystem.ts:396:31)
```

**Comment by kyaEH** [comment]
Same issue here

This is due to the new grid system for V12
[Foundry Git reference](https://github.com/foundryvtt/foundryvtt/discussions/10184)

If you want a quick-but-not-nice fix, delete this line in ruler.js:108 
`if (d.x === this.destination.x && d.y === this.destination.y) return;`

Seems that this.destination is always null / undefined.

**Comment by apoapostolov** [comment]
Thank you. I'll wait for an actual fix as I'm not migrating for at least
months.

**Comment by Spaceferret42** [comment]
It appears the fix works for square grid maps but it is still broken for hex grid maps

**Comment by kyaEH** [comment]
The fix that I done, which works for now on my side for square grid:
Replaced line 108 in ruler.js
`if (d.x === this.destination.x && d.y === this.destination.y) return;`
By 
`if ( this.destination && (d.x === this.destination.x) && (d.y === this.destination.y)) return;`

Removed all things related to force, and passed it to false
![image](https://github.com/manuelVo/foundryvtt-drag-ruler/assets/57956860/0cfac47d-de3d-46f2-9ddb-462a59424f72)

and in the _endMeasurement, added a this.clear();
![image](https://github.com/manuelVo/foundryvtt-drag-ruler/assets/57956860/449cc520-7f53-4303-9a1b-6910efb43694)

**Comment by manuelVo** [comment]
A v12 compatible version is now released.
