### ISSUE TITLE
Only happens in existing World, not new ones

### ISSUE THREAD

**Issue by ThreeofSwords** [manuelVo/foundryvtt-drag-ruler#331]
I only have one existing game.  If I enable Drag Ruler as the only module (besides socketlib, of course) and move a token, it throws the following error and does not work.  If I create a new game, it seems to work just fine.

Error: You are accessing the Actor5e "data" field of which was deprecated in v10 and replaced with "system". Continued usage of pre-v10 ".data" paths is no longer supported"
    at get data (foundry-esm.js:12036:15)
    at Object.getProperty (foundry-esm.js:3142:41)
    at GenericSpeedProvider.getRanges (speed_provider.js:118:47)
    at getRangesFromSpeedProvider (api.js:90:39)
    at DragRulerRuler.dragRulerGetColorForDistance (ruler.js:473:28)
    at DragRulerRuler.highlightMeasurementNative (foundry_imports.js:197:22)
    at DragRulerRuler.performPostPathfindingActions (ruler.js:200:34)
    at DragRulerRuler.measure (ruler.js:146:16)
    at DragRulerRuler.scheduleMeasurement (foundry_imports.js:157:8)
    at DragRulerRuler.onMouseMove (foundry_imports.js:149:22)

**Comment by manuelVo** [comment]
Check your speed provider settings. The setting "Speed Attribute" contains an old value that is no longer supported. To fix this, do the following:

1. Generate a new world using the same game system.
2. Open the Speed Provider Settings in the new world
3. Copy the "Speed Attribute"
4. Switch to the old world and open the Speed Provider Settings there
5. Paste the value in to the "Speed Attribute"

That should get rid of the error.

**Comment by ThreeofSwords** [comment]
> Check your speed provider settings. The setting "Speed Attribute" contains an old value that is no longer supported. To fix this, do the following:
That was the issue.  Thank you very much!
