### ISSUE TITLE
Drag Ruler Broken in PF2E in Foundry V12

### ISSUE THREAD

**Issue by MichaelPMattaini** [manuelVo/foundryvtt-drag-ruler#338]
In Pathfinder 2e world where Drag Ruler (and its dependencies) are the only active modules, trying to move a token throws the following:

```
pf2e.mjs:1341 Uncaught TypeError: Receiver must be class RulerPF2e
    at get canMeasure (pf2e.mjs:1341:346204)
    at TokenPF2e._propagateLeftClick (foundry.js:61271:37)
    at TokenPF2e._onClickLeft (foundry.js:27174:16)
    at TokenPF2e._onClickLeft (foundry.js:61266:11)
    at MouseInteractionManager.callback (foundry.js:30691:17)
    at #handleClickLeft (foundry.js:30892:15)
    at #handleLeftDown (foundry.js:30874:38)
    at #handlePointerDown (foundry.js:30838:58)
    at vh.notifyListeners (EventBoundary.ts:1454:26)
    at vh.notifyTarget (EventBoundary.ts:662:18)
pf2e.mjs:1341 Uncaught TypeError: Receiver must be class RulerPF2e
    at get canMeasure (pf2e.mjs:1341:346204)
    at TokenPF2e._propagateLeftClick (foundry.js:61271:37)
    at TokenPF2e._onClickLeft (foundry.js:27174:16)
    at TokenPF2e._onClickLeft (foundry.js:61266:11)
    at MouseInteractionManager.callback (foundry.js:30691:17)
    at #handleClickLeft (foundry.js:30892:15)
    at #handleLeftDown (foundry.js:30874:38)
    at #handlePointerDown (foundry.js:30838:58)
    at vh.notifyListeners (EventBoundary.ts:1454:26)
    at vh.notifyTarget (EventBoundary.ts:662:18)
pf2e.mjs:1341 Uncaught TypeError: Receiver must be class RulerPF2e
    at get canMeasure (pf2e.mjs:1341:346204)
    at TokenPF2e._propagateLeftClick (foundry.js:61271:37)
    at TokenPF2e._onClickLeft (foundry.js:27174:16)
    at TokenPF2e._onClickLeft (foundry.js:61266:11)
    at MouseInteractionManager.callback (foundry.js:30691:17)
    at #handleClickLeft (foundry.js:30892:15)
    at #handleLeftDown (foundry.js:30874:38)
    at #handlePointerDown (foundry.js:30838:58)
    at vh.notifyListeners (EventBoundary.ts:1454:26)
    at vh.notifyTarget (EventBoundary.ts:662:18)
get canMeasure @ pf2e.mjs:1341
_propagateLeftClick @ foundry.js:61271
_onClickLeft @ foundry.js:27174
_onClickLeft @ foundry.js:61266
callback @ foundry.js:30691
#handleClickLeft @ foundry.js:30892
#handleLeftDown @ foundry.js:30874
#handlePointerDown @ foundry.js:30838
notifyListeners @ EventBoundary.ts:1454
notifyTarget @ EventBoundary.ts:662
propagate @ EventBoundary.ts:299
dispatchEvent @ EventBoundary.ts:210
mapPointerDown @ EventBoundary.ts:683
mapEvent @ EventBoundary.ts:231
onPointerDown @ EventSystem.ts:373
```

**Comment by MichaelPMattaini** [comment]
Closing. This is due to PF2E drag ruler integration not having updated. Sorry.
